# To use with docker-compose add labels: section to your docker-compose.yml file

version: "2.1"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8081:81"
    # This container's 80 and 81 ports will be allowed on UFW firewall
    labels:
        UFW_MANAGED: "TRUE"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge