name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.23.x
          - 1.24.x
        platform:
          - ubuntu-22.04
    runs-on: "${{ matrix.platform }}"
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go-version }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verification
        run: go mod verify

      - name: Build
        run: go build -o ufw-docker-automated github.com/shinebayar-g/ufw-docker-automated
